[theme]

base = '#005392'

# Primary accent for interactive elements
primaryColor = '#005392'

# Background color for the main content area
backgroundColor = 'white'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#ccccccff'

# Color used for almost all text
textColor = 'black'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"